apiVersion: v1
kind: pod
metadata:
  name: nginx
  labels:
    project: roboshop
    purpose: mutli-containers-creation-demo
spec:
  containers:
  - name: nginx
    image: nginx
  - name: almalinux
    image: almalinux:9
    command: ["sleep", "1000"]  # continer busy - other wise contriner will goes to CrashLoopBack