apiVersion: v1
kind: Pod
metadata:
  name: env-configMapRef
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - secretRef:
        name: pod-secret  # secret name i.e metadata name:pod-secret 11.pod-secret.yaml