apiVersion: v1
kind: Service
metadata:
  name: nginx-NP
  labels:
    purpose: service-NP-demo
spec:  #so the Service will route traffic to this ,Pod which haveing the same lables
  type: NodePort
  selector:
    purpose: service-NP-demo
    project: roboshop
    env: dev
  ports:
    - protocol: TCP
      port: 80  #nginx service port
      targetPort: 80 #nginx container port

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    purpose: service-NP-demo
    project: roboshop
    env: dev
spec:
  contianers:
  - name: nginx
    image: nginx
